# -----------------------------------------
# Script to clean up excess files generated
# by RStudio and Knitr.
# -----------------------------------------


# Clean up dot files created by RStudio
rm -r .R*

# Trash reports generated by RMarkdown. This convention assumes
# that worthwhile files are being moved out of this folder and
# into the 'reports' directory.
rm -r *.html
rm -r *.pdf

# Remove directories with support documents generated by RMarkdown
rm -r *_files